version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: dealership_db
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always

  backend:
    image: dealership_web
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dealership_web
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - static:/static
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static:/static
    depends_on:
      - backend

  redis:
    image: redis
    restart: always

  celery:
    restart: always
    build:
      context: .
    volumes:
      - ./src:/app
    depends_on:
      - redis
      - backend
    env_file:
      - .env

volumes:
  postgres_db:
  static: