# Generated by Django 4.2.2 on 2023-06-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="suppliercars",
            name="amount",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
